### ISSUE TITLE
when  I use  gtirb-pprinter jt.gtirb -b jtt    

### ISSUE THREAD

**Issue by penq123** [GrammaTech/gtirb-rewriting#11]
[INFO]  Reading GTIRB file:     "jt.gtirb"
[ERROR] GTIRB file could not be opened: ""jt.gtirb"".

**Comment by penq123** [comment]
> This issue is a bit vague. What is creating `jt.gtirb`? Can you attach that file to this issue?

Thanks, this problem has been solved!
Where can I find more examples of gtirb-rewriting, please?

**Comment by jranieri-grammatech** [comment]
https://github.com/GrammaTech/gtirb-stack-stamp/blob/master/gtirb_stack_stamp/stack_stamp.py is the only example I'm aware of that is open source.
