### ISSUE TITLE
Can I recognize a specific function and add some code?

### ISSUE THREAD

**Issue by penq123** [GrammaTech/gtirb-rewriting#12]
Can I recognize a specific function and add some code? For example, recognize a function called test() and add some instructions?How do I do that?

**Comment by jranieri-grammatech** [comment]
Assuming the binary has symbols and ddisasm performed function inference (the default), that's pretty straightforward. Here's an entirely untested program that I think should be close to what you're after.

```python
from gtirb_rewriting import (
    Pass,
    patch_constraints,
    Patch,
    SingleBlockScope,
    BlockPosition,
)
import gtirb_rewriting.driver


class NopTest(Pass):
    def begin_module(self, module, functions, context):
        func = next(func for func in functions if func.get_name() == "test")
        for block in func.get_entry_blocks:
            context.register_insert(
                SingleBlockScope(block, BlockPosition.ENTRY),
                Patch.from_function(self.nop_patch),
            )

    @patch_constraints()
    def nop_patch(self, insertion_context):
        return "nop"


if __name__ == "__main__":
    gtirb_rewriting.driver.main(NopTest)
```

**Comment by penq123** [comment]
File "ll.py", line 14, in begin_module
    for block in func.get_entry_blocks:
TypeError: 'method' object is not iterable

**Comment by penq123** [comment]
> Assuming the binary has symbols and ddisasm performed function inference (the default), that's pretty straightforward. Here's an entirely untested program that I think should be close to what you're after.
> 
> ```python
> from gtirb_rewriting import (
>     Pass,
>     patch_constraints,
>     Patch,
>     SingleBlockScope,
>     BlockPosition,
> )
> import gtirb_rewriting.driver
> 
> 
> class NopTest(Pass):
>     def begin_module(self, module, functions, context):
>         func = next(func for func in functions if func.get_name() == "test")
>         for block in func.get_entry_blocks:
>             context.register_insert(
>                 SingleBlockScope(block, BlockPosition.ENTRY),
>                 Patch.from_function(self.nop_patch),
>             )
> 
>     @patch_constraints()
>     def nop_patch(self, insertion_context):
>         return "nop"
> 
> 
> if __name__ == "__main__":
>     gtirb_rewriting.driver.main(NopTest)
> ```

File "ll.py", line 14, in begin_module
for block in func.get_entry_blocks:
TypeError: 'method' object is not iterable
