### ISSUE TITLE
CFI  directive lost in  rewrote binary

### ISSUE THREAD

**Issue by StarGazerM** [GrammaTech/gtirb-rewriting#4]
Hi:

I am trying to rewrite some c++ binary which contain exception handling, but  seems stack  unwinding always fails, and I found
     
https://github.com/GrammaTech/gtirb-rewriting/blob/main/gtirb_rewriting/rewriting.py#L1062
    
in code, will these CFI removing cause `.eh_frame` information lost?

**Comment by StarGazerM** [comment]
ah..... seems not working,  I saw cfi added, but seems still something wrong, cause segfault...

**Comment by StarGazerM** [comment]
Sorry for reply late, what I found is in below:

- Most of CFI info is added by ddisasm reading DWARF information and applying inference rules.
- if there is no insertion  at the start of a function call (this potentially break gcc's calling convention  prologue), all CFI seems works fine, and exception handler will work normally. 

So, how I solve it in my code is always throw error when insertion break function prologue and epilogue.
Maybe in master, CFI removing line can be commented, and throw warning/error when user  try to insert to a block has  `.cfi_startproc` in it?

**Comment by jranieri-grammatech** [comment]
This has been resolved in the latest release of gtirb-rewriting.
